### ISSUE TITLE
add support for TOX envs

### ISSUE THREAD

**Issue by netzulo** [netzulo/qalab#29]
# TODO

`tox -l` must have this environments

### Python

- [x] python v2.7 **py27**
- [x] python v3.4 **py34**
- [x] python v3.5 **py35**
- [x] python v3.6 **py36**

### Linters

+ [x] build docs with `pip install flake8`

### Documentation

+ [x] build docs with `pip install Sphinx`

### Qalab

- [x] selenium hub installation **selenium-hub**
- [x] selenium node installation **selenium-hub**
- [x] selendroid hub installation **selendroid-hub**
- [x] selendroid node installation **selendroid-node**
- [x] appium node installation **appium-node**

**Comment by netzulo** [comment]
closed at PR #31
